# Build settings
tile_order: ['company_admin', 'company_users']
specific_order: ['xsponse_service', 'digital_displays', 'vape_detect', 'button_consoles', 'relay_consoles']

defaults:
  -
    scope:
      path: "digital-displays"
      type: "pages"
    values:
      nav: digital_displays
  -
    scope:
      path: "general-ops"
      type: "pages"
    values:
      nav: general_ops
  -
    scope:
      path: "vape-detect"
      type: "pages"
    values:
      nav: vape_detect
  -
    scope:
      path: "button-consoles"
      type: "pages"
    values:
      nav: button_consoles
  -
    scope:
      path: "relay-consoles"
      type: "pages"
    values:
      nav: relay_consoles
